name: Bandit SAST

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.11"
      - run: pip install bandit
      - run: bandit -r . -x ./venv,./.git -f txt -ll || true
